timeout: 1800s
options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: gcr.io/cloud-builders/docker
    env:
      - DOCKER_BUILDKIT=1
    args:
      [
        "build",
        "--target",
        "gateway",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/kally/gateway:latest",
        ".",
      ]

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/kally/gateway:latest
